server:
  port: 8082
  servlet:
    context-path: /consumer
spring:
  application:
    name: fly-demo-consumer
  profiles:
    active: local
logging:
  file:
    path:
    name: chao-product.log
  level:
    com.alibaba.nacos.client.naming: error
