spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        group: dev
        namespace: public
        service: ${spring.application.name}
        username: nacos
        password: nacos
      config:
        enabled: false
